'use client';

import { useCallback, useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { BedDouble, Globe2, Info, Layers3, ListTree, MapPin } from 'lucide-react';
import { GlassTooltip } from '@/components/charts/glass-tooltip';
import { Card, CardBody, CardHeader } from '@/components/ui/card';
import { LEVEL_FA } from '@/lib/utils';

const subtitle = 'پیش‌بینی در سطح اقامتگاه تولید و به سطوح بالاتر تجمیع می‌شود (Bottom-Up)';
const footnote = 'بازه اطمینان سطوح بالاتر از جمع کران‌های سطح پایین به دست می‌آید. این کار همبستگی خطاها را فرض می‌گیرد و پهنای بازه را محافظه‌کارانه بیش‌برآورد می‌کند.';
const icons = { listing: BedDouble, destination: MapPin, category: Layers3, market: Globe2 };

export function ForecastHierarchyCard({ levels }: { levels: string[] }) {
  const tooltipRef = useRef<HTMLDivElement>(null); const [tip, setTip] = useState<{ content: ReactNode; rect: DOMRect; boundaryTop: number } | null>(null); const [tipPosition, setTipPosition] = useState<{ x: number; y: number } | null>(null); const [active, setActive] = useState<number | null>(null);
  const hide = useCallback(() => { setTip(null); setTipPosition(null); }, []);
  const show = useCallback((event: React.MouseEvent<HTMLElement> | React.FocusEvent<HTMLElement>, content: ReactNode) => { const card = event.currentTarget.closest('.hierarchy-card'); setTipPosition(null); setTip({ content, rect: event.currentTarget.getBoundingClientRect(), boundaryTop: (card?.getBoundingClientRect().top ?? 0) + 8 }); }, []);
  useLayoutEffect(() => { if (!tip || !tooltipRef.current) return; const box = tooltipRef.current.getBoundingClientRect(); const x = Math.max(8, Math.min(tip.rect.left + tip.rect.width / 2 - box.width / 2, window.innerWidth - box.width - 8)); const above = tip.rect.top - box.height - 10; setTipPosition({ x, y: above < Math.max(8, tip.boundaryTop) ? tip.rect.bottom + 10 : above }); }, [tip]);
  useEffect(() => { const dismiss = () => hide(); window.addEventListener('resize', dismiss); window.addEventListener('scroll', dismiss, true); return () => { window.removeEventListener('resize', dismiss); window.removeEventListener('scroll', dismiss, true); }; }, [hide]);
  return <Card className="hierarchy-card overflow-hidden"><CardHeader icon={<ListTree className="h-[19px] w-[19px]" />} title="سلسله‌مراتب پیش‌بینی" subtitle={<>{subtitle.replace(' (Bottom-Up)', '')} <bdi dir="ltr" className="hierarchy-bottom-up">(Bottom-Up)</bdi></>} /><CardBody className="hierarchy-card__body"><div className="hierarchy-stepper" data-active={active ?? undefined}><ol>{levels.map((level, index) => { const Icon = icons[level as keyof typeof icons] ?? Layers3; const terminal = index === levels.length - 1; const text = terminal ? footnote : subtitle; return <li key={level} className={terminal ? 'hierarchy-node hierarchy-node--terminal' : 'hierarchy-node'}><button type="button" onMouseEnter={(event) => { setActive(index); show(event, <p className="hierarchy-tooltip__text">{text}</p>); }} onMouseLeave={() => { setActive(null); hide(); }} onFocus={(event) => { setActive(index); show(event, <p className="hierarchy-tooltip__text">{text}</p>); }} onBlur={() => { setActive(null); hide(); }} onKeyDown={(event) => { if (event.key === 'Escape') { event.currentTarget.blur(); hide(); } }}><span className="hierarchy-node__icon"><Icon /></span><span>{LEVEL_FA[level] ?? level}</span><small>{new Intl.NumberFormat('fa-IR').format(index + 1)}</small></button>{index < levels.length - 1 ? <span aria-hidden="true" className="hierarchy-connector"><i /></span> : null}</li>; })}</ol></div><div className="hierarchy-footnote"><Info aria-hidden="true" /><p>بازه اطمینان سطوح بالاتر از جمع کران‌های سطح پایین به دست می‌آید. این کار همبستگی خطاها را فرض می‌گیرد و پهنای بازه را <strong>محافظه‌کارانه بیش‌برآورد می‌کند</strong>.</p></div>{tip ? <div ref={tooltipRef} aria-hidden="true" className={tipPosition ? 'hierarchy-floating-tooltip hierarchy-floating-tooltip--visible' : 'hierarchy-floating-tooltip'} style={tipPosition ? { left: tipPosition.x, top: tipPosition.y } : { visibility: 'hidden' }}><GlassTooltip>{tip.content}</GlassTooltip></div> : null}</CardBody></Card>;
}
