'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowUpRight, Download, ShieldCheck } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, ComposedChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { pol4 } from '@/lib/pol4/api';
import { API_BASE_URL } from '@/lib/api/client';
import { ThemeToggle } from '@/components/theme-toggle';

const number = (v: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(v);
const pct = (v: number | null | undefined) => v == null ? 'Unavailable' : `${(v * 100).toFixed(2)}%`;

export default function JuryPage() {
  const query = useQuery({ queryKey: ['pol4-jury'], queryFn: pol4.jury });
  const [province, setProvince] = useState('all');
  const [selectedCity, setSelectedCity] = useState<number | null>(null);
  const [inputs, setInputs] = useState({ before: 0, after: 0, hourly: 0, fee: 0 });
  const data = query.data?.data;
  if (query.isLoading) return <div className="jury-page" dir="ltr" role="status">Loading verified evidence…</div>;
  if (query.isError || !data) return <div className="jury-page" dir="ltr"><h1>Evidence unavailable</h1><p>{query.data?.detail ?? 'The evidence service could not be reached.'}</p><button onClick={() => query.refetch()}>Retry</button><p><Link href="/">Return to dashboard</Link></p></div>;
  const cities = data.decisions.filter(row => province === 'all' || row.province === province).slice(0, 15);
  const selected = cities.find(row => row.city_code === selectedCity) ?? cities[0];
  const labor = (inputs.before - inputs.after) * inputs.hourly * 52 / 12;
  const roiReady = inputs.before > 0 && inputs.hourly > 0;
  const healthy = data.submission.finite && data.submission.nonnegative && data.submission.observed_floor && data.submission.duplicate_keys === 0;
  return <div className="jury-page" dir="ltr" lang="en">
    <header className="jury-nav"><Link href="/"><ArrowLeft size={16} /> Demand dashboard</Link><span>NOVO PULSE / EVIDENCE ROOM</span><div><button onClick={() => window.print()}>Print pitch</button><ThemeToggle compact /></div></header>
    <section className="jury-hero">
      <div><p className="jury-eyebrow">Search interest → an informed destination review</p><h1>See demand forming.<br /><em>Decide with evidence.</em></h1><p className="jury-intro">A 30-day view of remaining search interest gives destination teams an earlier, auditable starting point for planning.</p><div className="jury-tags"><span>{data.scope.cities} cities</span><span>{data.scope.provinces.length} provinces</span><span>Historical snapshot · {data.cutoff}</span></div></div>
      <aside className="jury-proof"><ShieldCheck size={28} /><span>Validated competition export</span><strong>{number(data.submission.rows)}</strong><p>city × check-in predictions</p><small>{healthy ? 'Finite · nonnegative · observed floor preserved' : 'Validation needs attention'}</small><code title={data.submission.sha256}>SHA-256 {data.submission.sha256.slice(0, 18)}…</code></aside>
    </section>
    <section className="jury-section" aria-labelledby="accuracy-title"><div className="jury-section-heading"><span>01 / Proof</span><h2 id="accuracy-title">Accuracy, with its difficult window included.</h2></div>
      <div className="jury-metrics"><article><span>Five-fold WAPE</span><strong>{pct(data.performance.champion.wape)}</strong><small>Pickup baseline {pct(data.performance.baseline.wape)}</small></article><article><span>Relative improvement</span><strong>{pct(data.performance.relative_improvement)}</strong><small>Identical historical target grids</small></article><article><span>Without the shock fold</span><strong>{pct(data.shock.without_fold_wape)}</strong><small>Diagnostic only; excluded one of five folds</small></article><article><span>95% fold bootstrap interval</span><strong className="jury-range">{pct(data.performance.confidence_interval.lower)}–{pct(data.performance.confidence_interval.upper)}</strong><small>Uncertainty of pooled WAPE, not per-city bounds</small></article></div>
      <div className="jury-callout"><strong>The May 21 fold overlaps the June 13–24, 2025 war.</strong><p>It contributes {pct(data.shock.error_share)} of total absolute error. We retain it in the headline. Temporal overlap does not establish causation. <a href={data.shock.source} target="_blank" rel="noreferrer">Event source <ArrowUpRight size={13} /></a></p><p>Calibration selection using only earlier closed folds: WAPE {pct(data.performance.prequential_wape)}. Model specification itself was preselected.</p></div>
      <div className="jury-chart" role="img" aria-label="Champion and baseline WAPE across five folds, with May 2025 highlighted"><ResponsiveContainer width="100%" height={280}><BarChart data={data.performance.folds}><CartesianGrid vertical={false} strokeDasharray="3 5" /><XAxis dataKey="cutoff" /><YAxis tickFormatter={pct} width={65} /><Tooltip formatter={(v: number) => pct(v)} /><Legend /><Bar isAnimationActive={false} dataKey="baseline" name="Pickup baseline" fill="#94a3b8" radius={[4, 4, 0, 0]} /><Bar isAnimationActive={false} dataKey="champion" name="Submitted model" radius={[4, 4, 0, 0]}>{data.performance.folds.map(row => <Cell key={row.cutoff} fill={row.shock_overlap ? '#d97706' : '#2563eb'} />)}</Bar></BarChart></ResponsiveContainer></div>
    </section>
    <section className="jury-section" aria-labelledby="cluster-title"><div className="jury-section-heading"><span>02 / Scientific judgment</span><h2 id="cluster-title">We measured what clustering actually earns.</h2></div><p>Summing cities can cancel their errors before WAPE is calculated. The control sums the city model’s predictions onto exactly the same groups, separating this mechanical gain from modelling gain.</p>
      {data.clustering ? <><div className="jury-chart" role="img" aria-label="Clustered model WAPE compared with the aggregated city control"><ResponsiveContainer width="100%" height={280}><ComposedChart data={data.clustering.levels}><CartesianGrid vertical={false} strokeDasharray="3 5" /><XAxis dataKey="mean_groups" tickFormatter={(value) => Number(value).toFixed(0)} /><YAxis tickFormatter={pct} domain={['auto', 'auto']} width={65} /><Tooltip formatter={(v: number) => pct(v)} /><Legend /><Line isAnimationActive={false} dataKey="clustered_wape" name="Cluster model" stroke="#2563eb" strokeWidth={3} /><Line isAnimationActive={false} dataKey="control_wape" name="Aggregated city control" stroke="#0d9488" strokeWidth={2} strokeDasharray="5 4" /></ComposedChart></ResponsiveContainer></div><p className="jury-caption">{data.clustering.warning} The x-axis shows mean groups across folds. Current selected experiment arm: <strong>{data.clustering.selected_arm}</strong>. Practical blend gate: more than 1% relative WAPE gain; not a significance test.</p></> : <p>Clustering evidence has not been generated.</p>}
      {data.experiments ? <details className="jury-details" open><summary>Audit challengers · common five-fold city grid</summary><div className="jury-table-wrap"><table><thead><tr><th>Arm</th><th>Raw WAPE</th><th>Same cross-fitted calibration policy</th></tr></thead><tbody>{Object.entries(data.experiments.arms).map(([arm, value]) => <tr key={arm}><td>{arm}</td><td>{pct(value.raw.pooled.wape)}</td><td>{pct(value.calibrated.pooled.wape)}</td></tr>)}</tbody></table></div><p>Exploratory comparisons; the submitted model has not been replaced. Origin changes city-history statistics only. Pickup curves remain fitted at the fold cutoff.</p></details> : <p className="jury-caption">The audit challenger benchmark is not yet available in this evidence packet.</p>}
    </section>
    {data.uncertainty && <section className="jury-section"><div className="jury-section-heading"><span>Experimental uncertainty</span><h2>Coverage measured on later windows.</h2></div><p>Empirical residual bands for the city challenger, with {pct(data.uncertainty.nominal_coverage)} nominal coverage. Each fold uses only previously completed out-of-fold errors. These bands are separate from the submitted forecast; temporal dependence prevents a coverage guarantee.</p><div className="jury-table-wrap"><table><thead><tr><th>Fold</th><th>Rows with bands</th><th>Observed coverage</th><th>Mean width (searches)</th></tr></thead><tbody>{data.uncertainty.folds.map(row => <tr key={row.cutoff}><td>{row.cutoff}</td><td>{number(row.eligible_rows)}</td><td>{pct(row.observed_coverage)}</td><td>{row.mean_width == null ? 'No prior evidence' : number(row.mean_width)}</td></tr>)}</tbody></table></div></section>}
    {data.event_study && <details className="jury-details"><summary>Descriptive shock study · weekday and prior-year checks</summary><p>Ratios compare daily volume with pre-window weekday expectations and matched dates in the previous Jalali year. Neither comparison identifies a causal effect.</p><div className="jury-table-wrap"><table><thead><tr><th>Clock</th><th>Window</th><th>Days</th><th>Weekday-adjusted ratio</th><th>Prior-Jalali-year ratio</th></tr></thead><tbody>{data.event_study.summary.map(row => <tr key={`${row.clock}-${row.period}`}><td>{row.clock}</td><td>{row.period}</td><td>{row.days}</td><td>{row.weekday_adjusted_ratio.toFixed(2)}×</td><td>{row.matched_jalali_year_ratio.toFixed(2)}×</td></tr>)}</tbody></table></div></details>}
    <section className="jury-section" aria-labelledby="business-title"><div className="jury-section-heading"><span>03 / Business workflow</span><h2 id="business-title">An analyst’s review queue, ready to use.</h2></div><p>Prioritize destination reviews by forecast search volume. Check pickup and observation support, then join conversion, inventory and campaign costs before a spending decision. These are historical examples from the competition snapshot.</p>
      <div className="jury-controls"><label>Province <select aria-label="Province" value={province} onChange={e => { setProvince(e.target.value); setSelectedCity(null); }}><option value="all">All seven provinces</option>{data.scope.provinces.map(p => <option key={p} value={p}>{p}</option>)}</select></label><a className="jury-download" href={`${API_BASE_URL}/pol4/decision-queue.csv`}><Download size={16} /> Export all {data.decisions.length} city reviews</a></div>
      <div className="jury-workspace"><div className="jury-table-wrap"><table><caption>Top {cities.length} destinations in the selected scope</caption><thead><tr><th>Destination</th><th>Forecast searches</th><th>Observed / forecast</th><th>Pickup / expected</th></tr></thead><tbody>{cities.map(row => <tr key={row.city_code} className={selected?.city_code === row.city_code ? 'is-selected' : ''}><td><button aria-pressed={selected?.city_code === row.city_code} onClick={() => setSelectedCity(row.city_code)}>{row.city}</button><small>{row.province}</small></td><td>{number(row.predicted_demand)}</td><td>{pct(row.observed_share)}</td><td>{row.pickup_ratio == null ? 'No evidence' : `${row.pickup_ratio.toFixed(2)}×`}</td></tr>)}</tbody></table></div>
      {selected && <aside className="jury-action" aria-live="polite"><p className="jury-eyebrow">Review brief / {selected.city_code}</p><h3>{selected.city}</h3><p>{selected.action}</p><dl><dt>Owner</dt><dd>{selected.owner}</dd><dt>Peak check-in</dt><dd>{selected.peak_checkin}</dd><dt>Panel forecast share</dt><dd>{pct(selected.forecast_share)}</dd><dt>Evidence status</dt><dd>{selected.evidence_status}</dd><dt>Decision gate</dt><dd>{selected.required_before_spend}</dd></dl></aside>}</div>
    </section>
    <section className="jury-section"><div className="jury-section-heading"><span>04 / Commercial validation</span><h2>Prove the workflow before pricing the outcome.</h2></div><div className="jury-pilot"><article><b>Week 1 · Instrument</b><p>Destination growth lead and analyst define the existing planning workflow, baseline hours and a fixed review cohort. Log recommendations and decisions.</p></article><article><b>Week 2 · Shadow</b><p>Run alongside the current workflow. Measure forecast freshness, review time, errors and recommendation acceptance without changing spend.</p></article><article><b>Weeks 3–4 · Evaluate</b><p>Pre-register a controlled pilot using joined bookings, margin and inventory. Scale only with measured value and no material guardrail regression.</p></article></div>
      <div className="jury-calculator"><div><h3>Pilot economics worksheet</h3><p>User-entered labor assumptions only. All monetary values must use the same currency. This does not estimate booking lift or observed ROI.</p></div><div className="jury-inputs">{([{key:'before', label:'Current analyst hours / week'}, {key:'after', label:'Pilot analyst hours / week'}, {key:'hourly', label:'Loaded cost / hour'}, {key:'fee', label:'Monthly service + operating cost'}] as const).map(input => <label key={input.key}>{input.label}<input type="number" min="0" step="any" value={inputs[input.key]} onChange={e => setInputs({...inputs, [input.key]: Math.max(0, Number(e.target.value) || 0)})} /></label>)}</div><output aria-live="polite">{roiReady ? `Illustrative monthly net labor value: ${number(labor - inputs.fee)} currency units` : 'Enter workflow measurements to calculate a scenario.'}</output><small>(Current hours − pilot hours) × hourly cost × 52 ÷ 12 − monthly costs. Setup costs and booking effects excluded.</small></div>
    </section>
    <section className="jury-section"><div className="jury-section-heading"><span>05 / Trust</span><h2>Clear boundaries. Inspectable evidence.</h2></div><ul className="jury-limits">{data.limits.map(limit => <li key={limit}>{limit}</li>)}</ul><p>{data.trainset_recovery && Object.values(data.trainset_recovery.file_hash_matches).every(Boolean) ? `Recovered champion trainset: ${number(data.trainset_recovery.rows)} rows; every original file hash matches.` : 'Trainset reconstruction is not yet verified in this packet.'}</p><details className="jury-details"><summary>Source files and SHA-256 checksums</summary>{Object.entries(data.sources).map(([name, hash]) => <p key={name}><strong>{name}</strong><code>{hash}</code></p>)}</details><p className="jury-caption">Evidence generated {data.generated_at}. Source changes invalidate this packet. Forecast cutoff remains {data.cutoff}.</p></section>
  </div>;
}
